apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  ports:
    - port: 80
      targetPort: http # References the name 'http' in the Deployment
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
