services:
  redis:
    image: redis:8.0.6-alpine
    container_name: scopa2-redis
    restart: always
    command: >
      --requirepass "${REDIS_PASSWORD}"
    volumes:
      - ./redis_data:/data
    networks:
      - app-network
