ingress:
  host: "us.scopa.local"

db:
  localNode: "yb-tserver-2.yb-tservers.db.svc.cluster.local"
  backups: "yb-tserver-0.yb-tservers.db.svc.cluster.local,yb-tserver-1.yb-tservers.db.svc.cluster.local"
